bnlp_data_platform_etl:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASS') }}"
      port: "{{ int(env_var('DB_PORT')) | as_number }}"
      schema: dbt
      threads: 4
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev
dbt_etl:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      schema: dbt
      threads: 4
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev
